# These placeholders will be filled by the hosting platform settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# This ensures the database schema is created on the cloud
spring.jpa.hibernate.ddl-auto=update